# Generated by Django 2.0.10 on 2019-02-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20190202_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='unLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('explan', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
