# Generated by Django 2.0.10 on 2019-02-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_unlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unLike',
        ),
    ]
